#!/bin/bash


sudo make install -C /home/gor171/Backedup/atlantis/temp/trunk/atlantis

if [ $? -eq 0 ] ; then

atlantisMerged -i INIT_VMPA_Jan2015.nc 0 -o outputSETAS.nc -r VMPA_setas_run_no_migration.prm -f VMPA_setas_force_fish_Trunk.prm -p VMPA_setas_physics.prm -b VMPA_setas_biol_fishing_Trunk.prm -h VMPA_setas_harvest_F_Trunk.prm -s SETasGroupsDem_mergedSeasons.csv -q SETasFisheries.csv -d outputFolderPristine
else 
  echo 'Failed to compile trunk'  
fi




