/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_requests_2eproto__INCLUDED
#define PROTOBUF_C_requests_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Requests__Init Requests__Init;
typedef struct _Requests__RunNextTimeStep Requests__RunNextTimeStep;
typedef struct _Requests__Shutdown Requests__Shutdown;
typedef struct _Requests__GetBiomass Requests__GetBiomass;
typedef struct _Requests__GetMortality Requests__GetMortality;
typedef struct _Requests__GetDetritus Requests__GetDetritus;
typedef struct _Requests__SetBiomass Requests__SetBiomass;
typedef struct _Requests__SetMortality Requests__SetMortality;
typedef struct _Requests__SetDetritus Requests__SetDetritus;
typedef struct _Requests__Request Requests__Request;


/* --- enums --- */

typedef enum _Requests__Request__Type {
  REQUESTS__REQUEST__TYPE__INIT = 0,
  REQUESTS__REQUEST__TYPE__RUNNEXTTIMESTEP = 1,
  REQUESTS__REQUEST__TYPE__SHUTDOWN = 2,
  REQUESTS__REQUEST__TYPE__GETBIOMASS = 3,
  REQUESTS__REQUEST__TYPE__GETMORTALITY = 4,
  REQUESTS__REQUEST__TYPE__GETDETRITUS = 5,
  REQUESTS__REQUEST__TYPE__SETBIOMASS = 6,
  REQUESTS__REQUEST__TYPE__SETMORTALITY = 7,
  REQUESTS__REQUEST__TYPE__SETDETRITUS = 8
} Requests__Request__Type;

/* --- messages --- */

struct  _Requests__Init
{
  ProtobufCMessage base;
  char *timestep;
};
#define REQUESTS__INIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__init__descriptor) \
    , NULL }


struct  _Requests__RunNextTimeStep
{
  ProtobufCMessage base;
};
#define REQUESTS__RUN_NEXT_TIME_STEP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__run_next_time_step__descriptor) \
     }


struct  _Requests__Shutdown
{
  ProtobufCMessage base;
};
#define REQUESTS__SHUTDOWN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__shutdown__descriptor) \
     }


struct  _Requests__GetBiomass
{
  ProtobufCMessage base;
  char *groupid;
};
#define REQUESTS__GET_BIOMASS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__get_biomass__descriptor) \
    , NULL }


struct  _Requests__GetMortality
{
  ProtobufCMessage base;
  char *groupid;
};
#define REQUESTS__GET_MORTALITY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__get_mortality__descriptor) \
    , NULL }


struct  _Requests__GetDetritus
{
  ProtobufCMessage base;
  char *groupid;
};
#define REQUESTS__GET_DETRITUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__get_detritus__descriptor) \
    , NULL }


struct  _Requests__SetBiomass
{
  ProtobufCMessage base;
  char *groupid;
  size_t n_values;
  double *values;
};
#define REQUESTS__SET_BIOMASS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__set_biomass__descriptor) \
    , NULL, 0,NULL }


struct  _Requests__SetMortality
{
  ProtobufCMessage base;
  char *groupid;
  size_t n_values;
  double *values;
};
#define REQUESTS__SET_MORTALITY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__set_mortality__descriptor) \
    , NULL, 0,NULL }


struct  _Requests__SetDetritus
{
  ProtobufCMessage base;
  char *groupid;
  size_t n_values;
  double *values;
};
#define REQUESTS__SET_DETRITUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__set_detritus__descriptor) \
    , NULL, 0,NULL }


struct  _Requests__Request
{
  ProtobufCMessage base;
  Requests__Request__Type type;
  Requests__Init *init;
  Requests__RunNextTimeStep *runnext;
  Requests__Shutdown *shutdown;
  Requests__GetBiomass *getbiomass;
  Requests__GetMortality *getmortality;
  Requests__GetDetritus *getdetritus;
  Requests__SetBiomass *setbiomass;
  Requests__SetMortality *setmortality;
  Requests__SetDetritus *setdetritus;
};
#define REQUESTS__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&requests__request__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


/* Requests__Init methods */
void   requests__init__init
                     (Requests__Init         *message);
size_t requests__init__get_packed_size
                     (const Requests__Init   *message);
size_t requests__init__pack
                     (const Requests__Init   *message,
                      uint8_t             *out);
size_t requests__init__pack_to_buffer
                     (const Requests__Init   *message,
                      ProtobufCBuffer     *buffer);
Requests__Init *
       requests__init__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__init__free_unpacked
                     (Requests__Init *message,
                      ProtobufCAllocator *allocator);
/* Requests__RunNextTimeStep methods */
void   requests__run_next_time_step__init
                     (Requests__RunNextTimeStep         *message);
size_t requests__run_next_time_step__get_packed_size
                     (const Requests__RunNextTimeStep   *message);
size_t requests__run_next_time_step__pack
                     (const Requests__RunNextTimeStep   *message,
                      uint8_t             *out);
size_t requests__run_next_time_step__pack_to_buffer
                     (const Requests__RunNextTimeStep   *message,
                      ProtobufCBuffer     *buffer);
Requests__RunNextTimeStep *
       requests__run_next_time_step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__run_next_time_step__free_unpacked
                     (Requests__RunNextTimeStep *message,
                      ProtobufCAllocator *allocator);
/* Requests__Shutdown methods */
void   requests__shutdown__init
                     (Requests__Shutdown         *message);
size_t requests__shutdown__get_packed_size
                     (const Requests__Shutdown   *message);
size_t requests__shutdown__pack
                     (const Requests__Shutdown   *message,
                      uint8_t             *out);
size_t requests__shutdown__pack_to_buffer
                     (const Requests__Shutdown   *message,
                      ProtobufCBuffer     *buffer);
Requests__Shutdown *
       requests__shutdown__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__shutdown__free_unpacked
                     (Requests__Shutdown *message,
                      ProtobufCAllocator *allocator);
/* Requests__GetBiomass methods */
void   requests__get_biomass__init
                     (Requests__GetBiomass         *message);
size_t requests__get_biomass__get_packed_size
                     (const Requests__GetBiomass   *message);
size_t requests__get_biomass__pack
                     (const Requests__GetBiomass   *message,
                      uint8_t             *out);
size_t requests__get_biomass__pack_to_buffer
                     (const Requests__GetBiomass   *message,
                      ProtobufCBuffer     *buffer);
Requests__GetBiomass *
       requests__get_biomass__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__get_biomass__free_unpacked
                     (Requests__GetBiomass *message,
                      ProtobufCAllocator *allocator);
/* Requests__GetMortality methods */
void   requests__get_mortality__init
                     (Requests__GetMortality         *message);
size_t requests__get_mortality__get_packed_size
                     (const Requests__GetMortality   *message);
size_t requests__get_mortality__pack
                     (const Requests__GetMortality   *message,
                      uint8_t             *out);
size_t requests__get_mortality__pack_to_buffer
                     (const Requests__GetMortality   *message,
                      ProtobufCBuffer     *buffer);
Requests__GetMortality *
       requests__get_mortality__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__get_mortality__free_unpacked
                     (Requests__GetMortality *message,
                      ProtobufCAllocator *allocator);
/* Requests__GetDetritus methods */
void   requests__get_detritus__init
                     (Requests__GetDetritus         *message);
size_t requests__get_detritus__get_packed_size
                     (const Requests__GetDetritus   *message);
size_t requests__get_detritus__pack
                     (const Requests__GetDetritus   *message,
                      uint8_t             *out);
size_t requests__get_detritus__pack_to_buffer
                     (const Requests__GetDetritus   *message,
                      ProtobufCBuffer     *buffer);
Requests__GetDetritus *
       requests__get_detritus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__get_detritus__free_unpacked
                     (Requests__GetDetritus *message,
                      ProtobufCAllocator *allocator);
/* Requests__SetBiomass methods */
void   requests__set_biomass__init
                     (Requests__SetBiomass         *message);
size_t requests__set_biomass__get_packed_size
                     (const Requests__SetBiomass   *message);
size_t requests__set_biomass__pack
                     (const Requests__SetBiomass   *message,
                      uint8_t             *out);
size_t requests__set_biomass__pack_to_buffer
                     (const Requests__SetBiomass   *message,
                      ProtobufCBuffer     *buffer);
Requests__SetBiomass *
       requests__set_biomass__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__set_biomass__free_unpacked
                     (Requests__SetBiomass *message,
                      ProtobufCAllocator *allocator);
/* Requests__SetMortality methods */
void   requests__set_mortality__init
                     (Requests__SetMortality         *message);
size_t requests__set_mortality__get_packed_size
                     (const Requests__SetMortality   *message);
size_t requests__set_mortality__pack
                     (const Requests__SetMortality   *message,
                      uint8_t             *out);
size_t requests__set_mortality__pack_to_buffer
                     (const Requests__SetMortality   *message,
                      ProtobufCBuffer     *buffer);
Requests__SetMortality *
       requests__set_mortality__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__set_mortality__free_unpacked
                     (Requests__SetMortality *message,
                      ProtobufCAllocator *allocator);
/* Requests__SetDetritus methods */
void   requests__set_detritus__init
                     (Requests__SetDetritus         *message);
size_t requests__set_detritus__get_packed_size
                     (const Requests__SetDetritus   *message);
size_t requests__set_detritus__pack
                     (const Requests__SetDetritus   *message,
                      uint8_t             *out);
size_t requests__set_detritus__pack_to_buffer
                     (const Requests__SetDetritus   *message,
                      ProtobufCBuffer     *buffer);
Requests__SetDetritus *
       requests__set_detritus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__set_detritus__free_unpacked
                     (Requests__SetDetritus *message,
                      ProtobufCAllocator *allocator);
/* Requests__Request methods */
void   requests__request__init
                     (Requests__Request         *message);
size_t requests__request__get_packed_size
                     (const Requests__Request   *message);
size_t requests__request__pack
                     (const Requests__Request   *message,
                      uint8_t             *out);
size_t requests__request__pack_to_buffer
                     (const Requests__Request   *message,
                      ProtobufCBuffer     *buffer);
Requests__Request *
       requests__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   requests__request__free_unpacked
                     (Requests__Request *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Requests__Init_Closure)
                 (const Requests__Init *message,
                  void *closure_data);
typedef void (*Requests__RunNextTimeStep_Closure)
                 (const Requests__RunNextTimeStep *message,
                  void *closure_data);
typedef void (*Requests__Shutdown_Closure)
                 (const Requests__Shutdown *message,
                  void *closure_data);
typedef void (*Requests__GetBiomass_Closure)
                 (const Requests__GetBiomass *message,
                  void *closure_data);
typedef void (*Requests__GetMortality_Closure)
                 (const Requests__GetMortality *message,
                  void *closure_data);
typedef void (*Requests__GetDetritus_Closure)
                 (const Requests__GetDetritus *message,
                  void *closure_data);
typedef void (*Requests__SetBiomass_Closure)
                 (const Requests__SetBiomass *message,
                  void *closure_data);
typedef void (*Requests__SetMortality_Closure)
                 (const Requests__SetMortality *message,
                  void *closure_data);
typedef void (*Requests__SetDetritus_Closure)
                 (const Requests__SetDetritus *message,
                  void *closure_data);
typedef void (*Requests__Request_Closure)
                 (const Requests__Request *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor requests__init__descriptor;
extern const ProtobufCMessageDescriptor requests__run_next_time_step__descriptor;
extern const ProtobufCMessageDescriptor requests__shutdown__descriptor;
extern const ProtobufCMessageDescriptor requests__get_biomass__descriptor;
extern const ProtobufCMessageDescriptor requests__get_mortality__descriptor;
extern const ProtobufCMessageDescriptor requests__get_detritus__descriptor;
extern const ProtobufCMessageDescriptor requests__set_biomass__descriptor;
extern const ProtobufCMessageDescriptor requests__set_mortality__descriptor;
extern const ProtobufCMessageDescriptor requests__set_detritus__descriptor;
extern const ProtobufCMessageDescriptor requests__request__descriptor;
extern const ProtobufCEnumDescriptor    requests__request__type__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_requests_2eproto__INCLUDED */
