/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_responses_2eproto__INCLUDED
#define PROTOBUF_C_responses_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Responses__BooleanResponse Responses__BooleanResponse;
typedef struct _Responses__GetResponse Responses__GetResponse;
typedef struct _Responses__Error Responses__Error;
typedef struct _Responses__Response Responses__Response;


/* --- enums --- */

typedef enum _Responses__Response__Type {
  RESPONSES__RESPONSE__TYPE__BOOL = 0,
  RESPONSES__RESPONSE__TYPE__GET = 1,
  RESPONSES__RESPONSE__TYPE__ERROR = 2
} Responses__Response__Type;

/* --- messages --- */

struct  _Responses__BooleanResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean response;
};
#define RESPONSES__BOOLEAN_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&responses__boolean_response__descriptor) \
    , 0 }


struct  _Responses__GetResponse
{
  ProtobufCMessage base;
  size_t n_values;
  double *values;
};
#define RESPONSES__GET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&responses__get_response__descriptor) \
    , 0,NULL }


struct  _Responses__Error
{
  ProtobufCMessage base;
  char *reason;
};
#define RESPONSES__ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&responses__error__descriptor) \
    , NULL }


struct  _Responses__Response
{
  ProtobufCMessage base;
  Responses__Response__Type type;
  Responses__BooleanResponse *bool_;
  Responses__GetResponse *get;
  Responses__Error *error;
};
#define RESPONSES__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&responses__response__descriptor) \
    , 0, NULL, NULL, NULL }


/* Responses__BooleanResponse methods */
void   responses__boolean_response__init
                     (Responses__BooleanResponse         *message);
size_t responses__boolean_response__get_packed_size
                     (const Responses__BooleanResponse   *message);
size_t responses__boolean_response__pack
                     (const Responses__BooleanResponse   *message,
                      uint8_t             *out);
size_t responses__boolean_response__pack_to_buffer
                     (const Responses__BooleanResponse   *message,
                      ProtobufCBuffer     *buffer);
Responses__BooleanResponse *
       responses__boolean_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   responses__boolean_response__free_unpacked
                     (Responses__BooleanResponse *message,
                      ProtobufCAllocator *allocator);


/* Responses__GetResponse methods */
void   responses__get_response__init
                     (Responses__GetResponse         *message);
size_t responses__get_response__get_packed_size
                     (const Responses__GetResponse   *message);
size_t responses__get_response__pack
                     (const Responses__GetResponse   *message,
                      uint8_t             *out);
size_t responses__get_response__pack_to_buffer
                     (const Responses__GetResponse   *message,
                      ProtobufCBuffer     *buffer);
Responses__GetResponse *
       responses__get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   responses__get_response__free_unpacked
                     (Responses__GetResponse *message,
                      ProtobufCAllocator *allocator);
/* Responses__Error methods */
void   responses__error__init
                     (Responses__Error         *message);
size_t responses__error__get_packed_size
                     (const Responses__Error   *message);
size_t responses__error__pack
                     (const Responses__Error   *message,
                      uint8_t             *out);
size_t responses__error__pack_to_buffer
                     (const Responses__Error   *message,
                      ProtobufCBuffer     *buffer);
Responses__Error *
       responses__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   responses__error__free_unpacked
                     (Responses__Error *message,
                      ProtobufCAllocator *allocator);
/* Responses__Response methods */
void   responses__response__init
                     (Responses__Response         *message);
size_t responses__response__get_packed_size
                     (const Responses__Response   *message);
size_t responses__response__pack
                     (const Responses__Response   *message,
                      uint8_t             *out);
size_t responses__response__pack_to_buffer
                     (const Responses__Response   *message,
                      ProtobufCBuffer     *buffer);
Responses__Response *
       responses__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   responses__response__free_unpacked
                     (Responses__Response *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Responses__BooleanResponse_Closure)
                 (const Responses__BooleanResponse *message,
                  void *closure_data);
typedef void (*Responses__GetResponse_Closure)
                 (const Responses__GetResponse *message,
                  void *closure_data);
typedef void (*Responses__Error_Closure)
                 (const Responses__Error *message,
                  void *closure_data);
typedef void (*Responses__Response_Closure)
                 (const Responses__Response *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor responses__boolean_response__descriptor;
extern const ProtobufCMessageDescriptor responses__get_response__descriptor;
extern const ProtobufCMessageDescriptor responses__error__descriptor;
extern const ProtobufCMessageDescriptor responses__response__descriptor;
extern const ProtobufCEnumDescriptor    responses__response__type__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_responses_2eproto__INCLUDED */
