/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "requests.pb-c.h"
void   requests__init__init
                     (Requests__Init         *message)
{
  static Requests__Init init_value = REQUESTS__INIT__INIT;
  *message = init_value;
}
size_t requests__init__get_packed_size
                     (const Requests__Init *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__init__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__init__pack
                     (const Requests__Init *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__init__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__init__pack_to_buffer
                     (const Requests__Init *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__init__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__Init *
       requests__init__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__Init *)
     protobuf_c_message_unpack (&requests__init__descriptor,
                                allocator, len, data);
}
void   requests__init__free_unpacked
                     (Requests__Init *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__init__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__run_next_time_step__init
                     (Requests__RunNextTimeStep         *message)
{
  static Requests__RunNextTimeStep init_value = REQUESTS__RUN_NEXT_TIME_STEP__INIT;
  *message = init_value;
}
size_t requests__run_next_time_step__get_packed_size
                     (const Requests__RunNextTimeStep *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__run_next_time_step__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__run_next_time_step__pack
                     (const Requests__RunNextTimeStep *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__run_next_time_step__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__run_next_time_step__pack_to_buffer
                     (const Requests__RunNextTimeStep *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__run_next_time_step__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__RunNextTimeStep *
       requests__run_next_time_step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__RunNextTimeStep *)
     protobuf_c_message_unpack (&requests__run_next_time_step__descriptor,
                                allocator, len, data);
}
void   requests__run_next_time_step__free_unpacked
                     (Requests__RunNextTimeStep *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__run_next_time_step__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__shutdown__init
                     (Requests__Shutdown         *message)
{
  static Requests__Shutdown init_value = REQUESTS__SHUTDOWN__INIT;
  *message = init_value;
}
size_t requests__shutdown__get_packed_size
                     (const Requests__Shutdown *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__shutdown__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__shutdown__pack
                     (const Requests__Shutdown *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__shutdown__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__shutdown__pack_to_buffer
                     (const Requests__Shutdown *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__shutdown__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__Shutdown *
       requests__shutdown__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__Shutdown *)
     protobuf_c_message_unpack (&requests__shutdown__descriptor,
                                allocator, len, data);
}
void   requests__shutdown__free_unpacked
                     (Requests__Shutdown *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__shutdown__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__get_biomass__init
                     (Requests__GetBiomass         *message)
{
  static Requests__GetBiomass init_value = REQUESTS__GET_BIOMASS__INIT;
  *message = init_value;
}
size_t requests__get_biomass__get_packed_size
                     (const Requests__GetBiomass *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_biomass__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__get_biomass__pack
                     (const Requests__GetBiomass *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_biomass__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__get_biomass__pack_to_buffer
                     (const Requests__GetBiomass *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_biomass__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__GetBiomass *
       requests__get_biomass__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__GetBiomass *)
     protobuf_c_message_unpack (&requests__get_biomass__descriptor,
                                allocator, len, data);
}
void   requests__get_biomass__free_unpacked
                     (Requests__GetBiomass *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_biomass__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__get_mortality__init
                     (Requests__GetMortality         *message)
{
  static Requests__GetMortality init_value = REQUESTS__GET_MORTALITY__INIT;
  *message = init_value;
}
size_t requests__get_mortality__get_packed_size
                     (const Requests__GetMortality *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_mortality__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__get_mortality__pack
                     (const Requests__GetMortality *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_mortality__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__get_mortality__pack_to_buffer
                     (const Requests__GetMortality *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_mortality__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__GetMortality *
       requests__get_mortality__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__GetMortality *)
     protobuf_c_message_unpack (&requests__get_mortality__descriptor,
                                allocator, len, data);
}
void   requests__get_mortality__free_unpacked
                     (Requests__GetMortality *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_mortality__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__get_detritus__init
                     (Requests__GetDetritus         *message)
{
  static Requests__GetDetritus init_value = REQUESTS__GET_DETRITUS__INIT;
  *message = init_value;
}
size_t requests__get_detritus__get_packed_size
                     (const Requests__GetDetritus *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_detritus__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__get_detritus__pack
                     (const Requests__GetDetritus *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_detritus__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__get_detritus__pack_to_buffer
                     (const Requests__GetDetritus *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_detritus__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__GetDetritus *
       requests__get_detritus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__GetDetritus *)
     protobuf_c_message_unpack (&requests__get_detritus__descriptor,
                                allocator, len, data);
}
void   requests__get_detritus__free_unpacked
                     (Requests__GetDetritus *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__get_detritus__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__set_biomass__init
                     (Requests__SetBiomass         *message)
{
  static Requests__SetBiomass init_value = REQUESTS__SET_BIOMASS__INIT;
  *message = init_value;
}
size_t requests__set_biomass__get_packed_size
                     (const Requests__SetBiomass *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_biomass__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__set_biomass__pack
                     (const Requests__SetBiomass *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_biomass__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__set_biomass__pack_to_buffer
                     (const Requests__SetBiomass *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_biomass__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__SetBiomass *
       requests__set_biomass__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__SetBiomass *)
     protobuf_c_message_unpack (&requests__set_biomass__descriptor,
                                allocator, len, data);
}
void   requests__set_biomass__free_unpacked
                     (Requests__SetBiomass *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_biomass__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__set_mortality__init
                     (Requests__SetMortality         *message)
{
  static Requests__SetMortality init_value = REQUESTS__SET_MORTALITY__INIT;
  *message = init_value;
}
size_t requests__set_mortality__get_packed_size
                     (const Requests__SetMortality *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_mortality__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__set_mortality__pack
                     (const Requests__SetMortality *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_mortality__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__set_mortality__pack_to_buffer
                     (const Requests__SetMortality *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_mortality__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__SetMortality *
       requests__set_mortality__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__SetMortality *)
     protobuf_c_message_unpack (&requests__set_mortality__descriptor,
                                allocator, len, data);
}
void   requests__set_mortality__free_unpacked
                     (Requests__SetMortality *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_mortality__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__set_detritus__init
                     (Requests__SetDetritus         *message)
{
  static Requests__SetDetritus init_value = REQUESTS__SET_DETRITUS__INIT;
  *message = init_value;
}
size_t requests__set_detritus__get_packed_size
                     (const Requests__SetDetritus *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_detritus__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__set_detritus__pack
                     (const Requests__SetDetritus *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_detritus__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__set_detritus__pack_to_buffer
                     (const Requests__SetDetritus *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_detritus__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__SetDetritus *
       requests__set_detritus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__SetDetritus *)
     protobuf_c_message_unpack (&requests__set_detritus__descriptor,
                                allocator, len, data);
}
void   requests__set_detritus__free_unpacked
                     (Requests__SetDetritus *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__set_detritus__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   requests__request__init
                     (Requests__Request         *message)
{
  static Requests__Request init_value = REQUESTS__REQUEST__INIT;
  *message = init_value;
}
size_t requests__request__get_packed_size
                     (const Requests__Request *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t requests__request__pack
                     (const Requests__Request *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t requests__request__pack_to_buffer
                     (const Requests__Request *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Requests__Request *
       requests__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Requests__Request *)
     protobuf_c_message_unpack (&requests__request__descriptor,
                                allocator, len, data);
}
void   requests__request__free_unpacked
                     (Requests__Request *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &requests__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor requests__init__field_descriptors[1] =
{
  {
    "timestep",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Init, timestep),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requests__init__field_indices_by_name[] = {
  0,   /* field[0] = timestep */
};
static const ProtobufCIntRange requests__init__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor requests__init__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.Init",
  "Init",
  "Requests__Init",
  "requests",
  sizeof(Requests__Init),
  1,
  requests__init__field_descriptors,
  requests__init__field_indices_by_name,
  1,  requests__init__number_ranges,
  (ProtobufCMessageInit) requests__init__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requests__run_next_time_step__field_descriptors[0] =
{
};
static const unsigned requests__run_next_time_step__field_indices_by_name[] = {
};
#define requests__run_next_time_step__number_ranges NULL
const ProtobufCMessageDescriptor requests__run_next_time_step__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.RunNextTimeStep",
  "RunNextTimeStep",
  "Requests__RunNextTimeStep",
  "requests",
  sizeof(Requests__RunNextTimeStep),
  0,
  requests__run_next_time_step__field_descriptors,
  requests__run_next_time_step__field_indices_by_name,
  0,  requests__run_next_time_step__number_ranges,
  (ProtobufCMessageInit) requests__run_next_time_step__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requests__shutdown__field_descriptors[0] =
{
};
static const unsigned requests__shutdown__field_indices_by_name[] = {
};
#define requests__shutdown__number_ranges NULL
const ProtobufCMessageDescriptor requests__shutdown__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.Shutdown",
  "Shutdown",
  "Requests__Shutdown",
  "requests",
  sizeof(Requests__Shutdown),
  0,
  requests__shutdown__field_descriptors,
  requests__shutdown__field_indices_by_name,
  0,  requests__shutdown__number_ranges,
  (ProtobufCMessageInit) requests__shutdown__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requests__get_biomass__field_descriptors[1] =
{
  {
    "groupId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__GetBiomass, groupid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requests__get_biomass__field_indices_by_name[] = {
  0,   /* field[0] = groupId */
};
static const ProtobufCIntRange requests__get_biomass__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor requests__get_biomass__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.GetBiomass",
  "GetBiomass",
  "Requests__GetBiomass",
  "requests",
  sizeof(Requests__GetBiomass),
  1,
  requests__get_biomass__field_descriptors,
  requests__get_biomass__field_indices_by_name,
  1,  requests__get_biomass__number_ranges,
  (ProtobufCMessageInit) requests__get_biomass__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requests__get_mortality__field_descriptors[1] =
{
  {
    "groupId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__GetMortality, groupid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requests__get_mortality__field_indices_by_name[] = {
  0,   /* field[0] = groupId */
};
static const ProtobufCIntRange requests__get_mortality__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor requests__get_mortality__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.GetMortality",
  "GetMortality",
  "Requests__GetMortality",
  "requests",
  sizeof(Requests__GetMortality),
  1,
  requests__get_mortality__field_descriptors,
  requests__get_mortality__field_indices_by_name,
  1,  requests__get_mortality__number_ranges,
  (ProtobufCMessageInit) requests__get_mortality__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requests__get_detritus__field_descriptors[1] =
{
  {
    "groupId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__GetDetritus, groupid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requests__get_detritus__field_indices_by_name[] = {
  0,   /* field[0] = groupId */
};
static const ProtobufCIntRange requests__get_detritus__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor requests__get_detritus__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.GetDetritus",
  "GetDetritus",
  "Requests__GetDetritus",
  "requests",
  sizeof(Requests__GetDetritus),
  1,
  requests__get_detritus__field_descriptors,
  requests__get_detritus__field_indices_by_name,
  1,  requests__get_detritus__number_ranges,
  (ProtobufCMessageInit) requests__get_detritus__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requests__set_biomass__field_descriptors[2] =
{
  {
    "groupId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__SetBiomass, groupid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(Requests__SetBiomass, n_values),
    PROTOBUF_C_OFFSETOF(Requests__SetBiomass, values),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requests__set_biomass__field_indices_by_name[] = {
  0,   /* field[0] = groupId */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange requests__set_biomass__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor requests__set_biomass__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.SetBiomass",
  "SetBiomass",
  "Requests__SetBiomass",
  "requests",
  sizeof(Requests__SetBiomass),
  2,
  requests__set_biomass__field_descriptors,
  requests__set_biomass__field_indices_by_name,
  1,  requests__set_biomass__number_ranges,
  (ProtobufCMessageInit) requests__set_biomass__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requests__set_mortality__field_descriptors[2] =
{
  {
    "groupId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__SetMortality, groupid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(Requests__SetMortality, n_values),
    PROTOBUF_C_OFFSETOF(Requests__SetMortality, values),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requests__set_mortality__field_indices_by_name[] = {
  0,   /* field[0] = groupId */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange requests__set_mortality__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor requests__set_mortality__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.SetMortality",
  "SetMortality",
  "Requests__SetMortality",
  "requests",
  sizeof(Requests__SetMortality),
  2,
  requests__set_mortality__field_descriptors,
  requests__set_mortality__field_indices_by_name,
  1,  requests__set_mortality__number_ranges,
  (ProtobufCMessageInit) requests__set_mortality__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor requests__set_detritus__field_descriptors[2] =
{
  {
    "groupId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__SetDetritus, groupid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(Requests__SetDetritus, n_values),
    PROTOBUF_C_OFFSETOF(Requests__SetDetritus, values),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requests__set_detritus__field_indices_by_name[] = {
  0,   /* field[0] = groupId */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange requests__set_detritus__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor requests__set_detritus__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.SetDetritus",
  "SetDetritus",
  "Requests__SetDetritus",
  "requests",
  sizeof(Requests__SetDetritus),
  2,
  requests__set_detritus__field_descriptors,
  requests__set_detritus__field_indices_by_name,
  1,  requests__set_detritus__number_ranges,
  (ProtobufCMessageInit) requests__set_detritus__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue requests__request__type__enum_values_by_number[9] =
{
  { "INIT", "REQUESTS__REQUEST__TYPE__INIT", 0 },
  { "RUNNEXTTIMESTEP", "REQUESTS__REQUEST__TYPE__RUNNEXTTIMESTEP", 1 },
  { "SHUTDOWN", "REQUESTS__REQUEST__TYPE__SHUTDOWN", 2 },
  { "GETBIOMASS", "REQUESTS__REQUEST__TYPE__GETBIOMASS", 3 },
  { "GETMORTALITY", "REQUESTS__REQUEST__TYPE__GETMORTALITY", 4 },
  { "GETDETRITUS", "REQUESTS__REQUEST__TYPE__GETDETRITUS", 5 },
  { "SETBIOMASS", "REQUESTS__REQUEST__TYPE__SETBIOMASS", 6 },
  { "SETMORTALITY", "REQUESTS__REQUEST__TYPE__SETMORTALITY", 7 },
  { "SETDETRITUS", "REQUESTS__REQUEST__TYPE__SETDETRITUS", 8 },
};
static const ProtobufCIntRange requests__request__type__value_ranges[] = {
{0, 0},{0, 9}
};
const ProtobufCEnumValueIndex requests__request__type__enum_values_by_name[9] =
{
  { "GETBIOMASS", 3 },
  { "GETDETRITUS", 5 },
  { "GETMORTALITY", 4 },
  { "INIT", 0 },
  { "RUNNEXTTIMESTEP", 1 },
  { "SETBIOMASS", 6 },
  { "SETDETRITUS", 8 },
  { "SETMORTALITY", 7 },
  { "SHUTDOWN", 2 },
};
const ProtobufCEnumDescriptor requests__request__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "requests.Request.Type",
  "Type",
  "Requests__Request__Type",
  "requests",
  9,
  requests__request__type__enum_values_by_number,
  9,
  requests__request__type__enum_values_by_name,
  1,
  requests__request__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor requests__request__field_descriptors[10] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, type),
    &requests__request__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, init),
    &requests__init__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "runnext",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, runnext),
    &requests__run_next_time_step__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shutdown",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, shutdown),
    &requests__shutdown__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getBiomass",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, getbiomass),
    &requests__get_biomass__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getMortality",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, getmortality),
    &requests__get_mortality__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getDetritus",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, getdetritus),
    &requests__get_detritus__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setBiomass",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, setbiomass),
    &requests__set_biomass__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setMortality",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, setmortality),
    &requests__set_mortality__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setDetritus",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Requests__Request, setdetritus),
    &requests__set_detritus__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned requests__request__field_indices_by_name[] = {
  4,   /* field[4] = getBiomass */
  6,   /* field[6] = getDetritus */
  5,   /* field[5] = getMortality */
  1,   /* field[1] = init */
  2,   /* field[2] = runnext */
  7,   /* field[7] = setBiomass */
  9,   /* field[9] = setDetritus */
  8,   /* field[8] = setMortality */
  3,   /* field[3] = shutdown */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange requests__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor requests__request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "requests.Request",
  "Request",
  "Requests__Request",
  "requests",
  sizeof(Requests__Request),
  10,
  requests__request__field_descriptors,
  requests__request__field_indices_by_name,
  1,  requests__request__number_ranges,
  (ProtobufCMessageInit) requests__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
