/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "responses.pb-c.h"
void   responses__boolean_response__init
                     (Responses__BooleanResponse         *message)
{
  static Responses__BooleanResponse init_value = RESPONSES__BOOLEAN_RESPONSE__INIT;
  *message = init_value;
}
size_t responses__boolean_response__get_packed_size
                     (const Responses__BooleanResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__boolean_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t responses__boolean_response__pack
                     (const Responses__BooleanResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__boolean_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t responses__boolean_response__pack_to_buffer
                     (const Responses__BooleanResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__boolean_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Responses__BooleanResponse *
       responses__boolean_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Responses__BooleanResponse *)
     protobuf_c_message_unpack (&responses__boolean_response__descriptor,
                                allocator, len, data);
}
void   responses__boolean_response__free_unpacked
                     (Responses__BooleanResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__boolean_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   responses__get_response__init
                     (Responses__GetResponse         *message)
{
  static Responses__GetResponse init_value = RESPONSES__GET_RESPONSE__INIT;
  *message = init_value;
}
size_t responses__get_response__get_packed_size
                     (const Responses__GetResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t responses__get_response__pack
                     (const Responses__GetResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t responses__get_response__pack_to_buffer
                     (const Responses__GetResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Responses__GetResponse *
       responses__get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Responses__GetResponse *)
     protobuf_c_message_unpack (&responses__get_response__descriptor,
                                allocator, len, data);
}
void   responses__get_response__free_unpacked
                     (Responses__GetResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   responses__error__init
                     (Responses__Error         *message)
{
  static Responses__Error init_value = RESPONSES__ERROR__INIT;
  *message = init_value;
}
size_t responses__error__get_packed_size
                     (const Responses__Error *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t responses__error__pack
                     (const Responses__Error *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t responses__error__pack_to_buffer
                     (const Responses__Error *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Responses__Error *
       responses__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Responses__Error *)
     protobuf_c_message_unpack (&responses__error__descriptor,
                                allocator, len, data);
}
void   responses__error__free_unpacked
                     (Responses__Error *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   responses__response__init
                     (Responses__Response         *message)
{
  static Responses__Response init_value = RESPONSES__RESPONSE__INIT;
  *message = init_value;
}
size_t responses__response__get_packed_size
                     (const Responses__Response *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t responses__response__pack
                     (const Responses__Response *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t responses__response__pack_to_buffer
                     (const Responses__Response *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Responses__Response *
       responses__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Responses__Response *)
     protobuf_c_message_unpack (&responses__response__descriptor,
                                allocator, len, data);
}
void   responses__response__free_unpacked
                     (Responses__Response *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &responses__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor responses__boolean_response__field_descriptors[1] =
{
  {
    "response",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Responses__BooleanResponse, response),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned responses__boolean_response__field_indices_by_name[] = {
  0,   /* field[0] = response */
};
static const ProtobufCIntRange responses__boolean_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor responses__boolean_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "responses.BooleanResponse",
  "BooleanResponse",
  "Responses__BooleanResponse",
  "responses",
  sizeof(Responses__BooleanResponse),
  1,
  responses__boolean_response__field_descriptors,
  responses__boolean_response__field_indices_by_name,
  1,  responses__boolean_response__number_ranges,
  (ProtobufCMessageInit) responses__boolean_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor responses__get_response__field_descriptors[1] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(Responses__GetResponse, n_values),
    PROTOBUF_C_OFFSETOF(Responses__GetResponse, values),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned responses__get_response__field_indices_by_name[] = {
  0,   /* field[0] = values */
};
static const ProtobufCIntRange responses__get_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor responses__get_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "responses.GetResponse",
  "GetResponse",
  "Responses__GetResponse",
  "responses",
  sizeof(Responses__GetResponse),
  1,
  responses__get_response__field_descriptors,
  responses__get_response__field_indices_by_name,
  1,  responses__get_response__number_ranges,
  (ProtobufCMessageInit) responses__get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor responses__error__field_descriptors[1] =
{
  {
    "reason",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Responses__Error, reason),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned responses__error__field_indices_by_name[] = {
  0,   /* field[0] = reason */
};
static const ProtobufCIntRange responses__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor responses__error__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "responses.Error",
  "Error",
  "Responses__Error",
  "responses",
  sizeof(Responses__Error),
  1,
  responses__error__field_descriptors,
  responses__error__field_indices_by_name,
  1,  responses__error__number_ranges,
  (ProtobufCMessageInit) responses__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue responses__response__type__enum_values_by_number[3] =
{
  { "BOOL", "RESPONSES__RESPONSE__TYPE__BOOL", 0 },
  { "GET", "RESPONSES__RESPONSE__TYPE__GET", 1 },
  { "ERROR", "RESPONSES__RESPONSE__TYPE__ERROR", 2 },
};
static const ProtobufCIntRange responses__response__type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex responses__response__type__enum_values_by_name[3] =
{
  { "BOOL", 0 },
  { "ERROR", 2 },
  { "GET", 1 },
};
const ProtobufCEnumDescriptor responses__response__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "responses.Response.Type",
  "Type",
  "Responses__Response__Type",
  "responses",
  3,
  responses__response__type__enum_values_by_number,
  3,
  responses__response__type__enum_values_by_name,
  1,
  responses__response__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor responses__response__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Responses__Response, type),
    &responses__response__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Responses__Response, bool_),
    &responses__boolean_response__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Responses__Response, get),
    &responses__get_response__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Responses__Response, error),
    &responses__error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned responses__response__field_indices_by_name[] = {
  1,   /* field[1] = bool */
  3,   /* field[3] = error */
  2,   /* field[2] = get */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange responses__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor responses__response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "responses.Response",
  "Response",
  "Responses__Response",
  "responses",
  sizeof(Responses__Response),
  4,
  responses__response__field_descriptors,
  responses__response__field_indices_by_name,
  1,  responses__response__number_ranges,
  (ProtobufCMessageInit) responses__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
